plugins:
  - serverless-offline
  - serverless-dotenv-plugin
service: defimarket
useDotenv: true
provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  custom:
    region: ${opt:region, self:provider.region}
    stage: ${opt:stage, self:provider.stage}
  environment:
    AWS_STAGE: ${opt:stage}
    AWS_API_GATEWAY_URL:
      Fn::Join:
        - ""
        - - https://
          - Ref: ApiGatewayRestApi
          - .execute-api.${opt:region,
            self:provider.region}.amazonaws.com/${opt:stage,
            self:provider.stage}
resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: ApiGatewayRestApi
package:
  patterns:
    - "!./**"
    - dist/**/*.js
functions:
  steam_authenticate:
    handler: dist/lambdas/steam/authenticate.handler
    events:
      - http: ANY /steam/authenticate
        cors: true
  steam_inventory:
    handler: dist/lambdas/steam/inventory.handler
    events:
      - http: ANY /steam/inventory
        cors: true
  steam_validateTrade:
    handler: dist/lambdas/steam/validateTrade.handler
    events:
      - http: ANY /steam/validateTrade
        cors: true
  steam_verify:
    handler: dist/lambdas/steam/verify.handler
    events:
      - http: ANY /steam/verify
        cors: true
